#  Copyright 2019 U.C. Berkeley RISE Lab
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  Modifications copyright (C) 2021 Taras Lykhenko, Rafael Soares

apiVersion: v1
kind: Pod
metadata:
  name: management-pod
  labels:
    role: management
spec:
  restartPolicy: Never
  containers:
  - name: management-container
<<<<<<< HEAD
    image: pedro99p/faastcc_management
    imagePullPolicy: Never
=======
    image: jrafaelsoares/faastcc_management
    imagePullPolicy: IfNotPresent
>>>>>>> 7a09b7fc118cf92156de4332c667d22bfc579ddb
    env:
    - name: LIBC_FATAL_STDERR_
      value: "1"
    - name: REPO_ORG
      value: FaaSTCC
    - name: REPO_BRANCH
      value: main
    - name: ANNA_REPO_ORG
      value: FaaSTCC
    - name: ANNA_REPO_BRANCH
      value: master
<<<<<<< HEAD
=======
  imagePullSecrets:
    - name: regcred
  nodeSelector:
    type: S
>>>>>>> 7a09b7fc118cf92156de4332c667d22bfc579ddb
