#  Copyright 2019 U.C. Berkeley RISE Lab
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  Modifications copyright (C) 2021 Taras Lykhenko, Rafael Soares

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: routing-nodes
  labels: 
    role: routing
spec:
  selector:
    matchLabels:
      role: routing
  template:
    metadata:
      labels:
        role: routing
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              role: routing
      containers:
      - name: routing-container
<<<<<<< HEAD
        image: pedro99p/faastcc_anna
        imagePullPolicy: Never
=======
        image: jrafaelsoares/faastcc_anna
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "4G"
            cpu: "4"
          limits:
            cpu: "8"
>>>>>>> 7a09b7fc118cf92156de4332c667d22bfc579ddb
        env:
        - name: LIBC_FATAL_STDERR_
          value: "1"
        - name: SERVER_TYPE
          value: r
        - name: MON_IPS
          value: MON_IPS_DUMMY
        - name: REPO_ORG
          value: FaaSTCC
        - name: REPO_BRANCH
<<<<<<< HEAD
          value: master
=======
          value: master
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        type: S
>>>>>>> 7a09b7fc118cf92156de4332c667d22bfc579ddb
